name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latestA
    name: Testing
    steps:
      - uses: actions/checkout@v3
      - name: "Run script"
        run: ./check-code.sh

